mysql
CREATE USER 'root'@'%' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}' ;
GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION ;
CREATE DATABASE IF NOT EXISTS Contact;
CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}' ;
GRANT ALL ON Contact.* TO '${MYSQL_USER}'@'%' ;
FLUSH PRIVILEGES ;
CREATE TABLE Contacts ( Username VARCHAR(100), Age INT, Phonenumber VARCHAR(10), Address VARCHAR(100) );